# Generated by Django 2.1 on 2018-09-29 20:15

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('department', models.TextField()),
                ('office', models.TextField()),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mtype', models.TextField()),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('keywords', models.TextField()),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('identifier', models.TextField()),
                ('accessLevel', models.TextField()),
                ('bureauCode', models.TextField()),
                ('programCode', models.TextField()),
                ('license', models.TextField()),
                ('spatial', models.TextField()),
                ('temporal', models.TextField()),
                ('describedByType', models.TextField()),
                ('describedBy', models.TextField()),
                ('accrualPeriodicity', models.TextField(null=True)),
                ('conformsTo', models.TextField(null=True)),
                ('dataQuality', models.TextField(null=True)),
                ('isPartOf', models.TextField(null=True)),
                ('issued', models.TextField(null=True)),
                ('language', models.TextField(null=True)),
                ('landingPage', models.TextField(null=True)),
                ('primaryITInvestment', models.TextField(null=True)),
                ('references', models.TextField(null=True)),
                ('systemOfRecords', models.TextField(null=True)),
                ('theme', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mtype', models.TextField()),
                ('accessURL', models.TextField()),
                ('conformsTo', models.TextField()),
                ('describedBy', models.TextField()),
                ('describedByType', models.TextField()),
                ('description', models.TextField()),
                ('downloadURL', models.TextField()),
                ('dformat', models.TextField()),
                ('mediaType', models.TextField()),
                ('title', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.AddField(
            model_name='dataset',
            name='distribution',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cataloger.Distribution'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='publisher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dataset',
            name='schema',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cataloger.Schema'),
        ),
    ]
