# Generated by Django 2.1.2 on 2018-11-08 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cataloger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='References',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='references',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='theme',
        ),
        migrations.AddField(
            model_name='dataset',
            name='references',
            field=models.ManyToManyField(blank=True, to='cataloger.References'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='theme',
            field=models.ManyToManyField(blank=True, to='cataloger.Theme'),
        ),
    ]
