# Generated by Django 2.1.2 on 2018-10-29 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cataloger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_context', models.URLField(default='https://project-open-data.cio.gov/v1.1/schema/catalog.jsonld')),
                ('_id', models.URLField(default='https://opendatapdx.herokuapp.com/api/')),
                ('_type', models.CharField(default='dcat:Catalog', max_length=12)),
                ('_conformsTo', models.URLField(default='https://project-open-data.cio.gov/v1.1/schema')),
                ('describedBy', models.URLField(default='https://project-open-data.cio.gov/v1.1/schema/catalog.json')),
            ],
        ),
        migrations.RenameField(
            model_name='dataset',
            old_name='keywords',
            new_name='keyword',
        ),
        migrations.AddField(
            model_name='catalog',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cataloger.Dataset'),
        ),
    ]
