# Generated by Django 2.1.1 on 2018-10-02 06:33

import cataloger.managers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cataloger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BureauCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.TextField()),
                ('description', models.TextField(null=True)),
                ('bureau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cataloger.BureauCode')),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office', models.TextField()),
                ('description', models.TextField(null=True)),
                ('bureau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cataloger.BureauCode')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cataloger.Division')),
            ],
        ),
        migrations.AlterModelManagers(
            name='profile',
            managers=[
                ('objects', cataloger.managers.ProfileManager()),
            ],
        ),
    ]
