# Generated by Django 2.1.2 on 2018-11-11 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cataloger', '0002_auto_20181108_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='published',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='bureauCode',
            field=models.ManyToManyField(help_text='To select multiple bureau codes, use <b>CTRL + Click</b> on Windows or <b>CMD + Click</b> on MacOS.', to='cataloger.BureauCode'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='keyword',
            field=models.ManyToManyField(help_text='To select multiple keywords, use <b>CTRL + Click</b> on Windows or <b>CMD + Click</b> on MacOS.', to='cataloger.Keyword'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='language',
            field=models.ManyToManyField(blank=True, help_text='To select multiple languages, use <b>CTRL + Click</b> on Windows or <b>CMD + Click</b> on MacOS.', to='cataloger.Language'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='programCode',
            field=models.ManyToManyField(help_text='To select multiple program codes, use <b>CTRL + Click</b> on Windows or <b>CMD + Click</b> on MacOS.', to='cataloger.Division'),
        ),
    ]
