# Generated by Django 2.1.1 on 2018-10-03 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cataloger', '0002_auto_20181002_0633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='department',
        ),
        migrations.AlterField(
            model_name='profile',
            name='office',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cataloger.Office'),
        ),
    ]
