# Generated by Django 2.1.2 on 2018-11-02 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cataloger', '0002_dataset_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='accessLevel',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to='cataloger.AccessLevel'),
        ),
    ]
