# Generated by Django 2.1.1 on 2018-10-03 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cataloger', '0003_auto_20181003_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='office',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='cataloger.Office'),
        ),
    ]
