# Generated by Django 2.1.2 on 2018-11-04 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cataloger', '0003_auto_20181102_0305'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='url',
            field=models.URLField(default=None),
            preserve_default=False,
        ),
    ]
