# Generated by Django 2.1.2 on 2018-10-30 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cataloger', '0004_dataset_rights'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog',
            name='dataset',
        ),
        migrations.AddField(
            model_name='catalog',
            name='dataset',
            field=models.ManyToManyField(to='cataloger.Dataset'),
        ),
    ]
