# Generated by Django 2.1.1 on 2018-10-03 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cataloger', '0004_auto_20181003_0524'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bureau',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cataloger.BureauCode'),
        ),
        migrations.AddField(
            model_name='profile',
            name='division',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cataloger.Division'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='office',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cataloger.Office'),
        ),
    ]
