# Generated by Django 2.1.2 on 2018-10-07 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cataloger', '0006_auto_20181004_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bureau',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cataloger.BureauCode'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cataloger.Division'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cataloger.Office'),
        ),
    ]
