# Generated by Django 2.1.2 on 2018-10-07 23:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cataloger', '0007_auto_20181007_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='publisher',
        ),
        migrations.AddField(
            model_name='dataset',
            name='publisher',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
